version: '3'

services:
  app:
    build: ./DOCKER
    command: python FlaskProjectFirst/app.py
    volumes:
      - .:/FlaskProjectFirst
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    restart: always